/**
 * ═══════════════════════════════════════════════════════════════════════════
 * WORK CARD COMPONENT
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Reusable card component for displaying project thumbnails.
 * This component automatically handles:
 * - External links (Behance/Dribbble) vs internal links
 * - Different image types (URL, Figma asset, or React component)
 * - Hover effects and animations
 * 
 * ⚠️ DO NOT EDIT THIS FILE unless you want to change the card design
 * To add/edit projects, go to: /data/projects.ts
 * 
 * ═══════════════════════════════════════════════════════════════════════════
 */

import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'motion/react';
import { ArrowUpRight } from 'lucide-react';
import type { Project } from '../../types';

interface WorkCardProps {
  project: Project;
}

export function WorkCard({ project }: WorkCardProps) {
  // ─────────────────────────────────────────────────────────────────────────
  // Determine card size class
  // ─────────────────────────────────────────────────────────────────────────
  const sizeClass = project.size === 'large' 
    ? 'md:col-span-2 aspect-[16/9]' 
    : 'aspect-[4/5]';

  // ─────────────────────────────────────────────────────────────────────────
  // Render the project image based on type
  // ─────────────────────────────────────────────────────────────────────────
  const renderImage = () => {
    // Case 1: React Component (imported Figma SVG components)
    if (project.imageType === 'component' && project.imageComponent) {
      const Component = project.imageComponent;
      return (
        <div className="w-full h-full relative overflow-hidden">
          <div className="absolute inset-0 bg-black/5 group-hover:bg-black/10 transition-colors z-10" />
          <div className="w-full h-full transition-transform duration-700 group-hover:scale-105 origin-center">
            <svg 
              viewBox={project.svgViewBox || "0 0 1920 1080"} 
              className="w-full h-full" 
              preserveAspectRatio="xMidYMid slice"
            >
              <foreignObject width="100%" height="100%">
                <Component />
              </foreignObject>
            </svg>
          </div>
        </div>
      );
    }
    
    // Case 2: Figma Asset (imported image file)
    if (project.imageType === 'figma' && project.figmaAsset) {
      return (
        <div className="w-full h-full relative overflow-hidden">
          <div className="absolute inset-0 bg-black/5 group-hover:bg-black/10 transition-colors z-10" />
          <div className="w-full h-full transition-transform duration-700 group-hover:scale-105 origin-center">
            <img 
              src={project.figmaAsset} 
              alt={project.title} 
              className="w-full h-full object-cover" 
            />
          </div>
        </div>
      );
    }
    
    // Case 3: URL (direct image link)
    if (project.imageType === 'url' && project.image) {
      return (
        <>
          <div className="absolute inset-0 bg-black/5 group-hover:bg-black/10 transition-colors z-10" />
          <img 
            src={project.image} 
            alt={project.title}
            className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
          />
        </>
      );
    }

    // Fallback: Empty gray box
    return (
      <div className="w-full h-full bg-gray-200 flex items-center justify-center">
        <p className="text-gray-400">No image</p>
      </div>
    );
  };

  // ─────────────────────────────────────────────────────────────────────────
  // Render card content (title, category, metric, arrow)
  // ─────────────────────────────────────────────────────────────────────────
  const cardContent = (
    <>
      {renderImage()}
      <div className="absolute bottom-0 left-0 p-8 z-20 w-full bg-gradient-to-t from-white/90 to-transparent">
        <div className="flex justify-between items-end">
          <div>
            <p className="text-black/60 font-medium mb-1">{project.category}</p>
            <h3 className="text-2xl md:text-3xl font-bold text-black">{project.title}</h3>
            <p className="text-black/60 text-sm mt-2">{project.metric}</p>
          </div>
          <div className="w-12 h-12 rounded-full bg-white/80 backdrop-blur-md flex items-center justify-center group-hover:bg-black group-hover:text-white transition-all shadow-sm">
            <ArrowUpRight className="w-5 h-5" />
          </div>
        </div>
      </div>
    </>
  );

  // ─────────────────────────────────────────────────────────────────────────
  // Wrapper: External link or internal link
  // ─────────────────────────────────────────────────────────────────────────
  // Support both 'link' and 'externalLink' for backwards compatibility
  const projectLink = project.link || project.externalLink;
  
  const cardWrapper = projectLink ? (
    // External link (Behance/Dribbble/Live Site) - opens in new tab
    <a 
      href={projectLink}
      target="_blank"
      rel="noopener noreferrer"
      className="block w-full h-full"
    >
      {cardContent}
    </a>
  ) : (
    // No link - just show the card (could be changed to internal detail page later)
    <div className="block w-full h-full">
      {cardContent}
    </div>
  );

  // ─────────────────────────────────────────────────────────────────────────
  // Return animated card
  // ─────────────────────────────────────────────────────────────────────────
  return (
    <motion.div
      layout
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{ duration: 0.3 }}
      className={`group relative cursor-pointer ${sizeClass} rounded-xl overflow-hidden bg-gray-100`}
    >
      {cardWrapper}
    </motion.div>
  );
}