/**
 * ═══════════════════════════════════════════════════════════════════════════
 * FEATURED WORK SECTION - Homepage Carousel
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * This component displays a carousel of random projects on the homepage.
 * All project data comes from: /data/projects.ts
 * 
 * ⚠️ TO ADD/EDIT PROJECTS: Go to /data/projects.ts
 * ⚠️ DO NOT EDIT THIS FILE unless you want to change the carousel behavior
 * 
 * ═══════════════════════════════════════════════════════════════════════════
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { ArrowUpRight, Loader2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../ui/button';
import { useProjects } from '../../hooks/useProjects';
import { AnimatedSection, AnimatedText } from '../shared/AnimatedSection';
import { ScrambleText } from '../shared/ScrambleText';
import type { Project } from '../../types';

// ═══════════════════════════════════════════════════════════════════════════
// HELPER: Render Project Image
// Handles different image types (URL, Figma asset, React component)
// ═══════════════════════════════════════════════════════════════════════════
const renderProjectImage = (project: Project) => {
  // Case 1: React Component (imported Figma SVG components)
  if (project.imageType === 'component' && project.imageComponent) {
    const Component = project.imageComponent;
    return (
      <svg 
        viewBox={project.svgViewBox || "0 0 1920 1080"} 
        className="w-full h-full" 
        preserveAspectRatio="xMidYMid slice"
      >
        <foreignObject width="100%" height="100%">
          <Component />
        </foreignObject>
      </svg>
    );
  }
  
  // Case 2: Figma Asset (imported image file)
  if (project.imageType === 'figma' && project.figmaAsset) {
    return (
      <img 
        src={project.figmaAsset} 
        alt={project.title} 
        className="w-full h-full object-cover" 
      />
    );
  }
  
  // Case 3: URL (direct image link)
  if (project.imageType === 'url' && project.image) {
    return (
      <img 
        src={project.image} 
        alt={project.title}
        className="w-full h-full object-cover"
      />
    );
  }

  // Fallback
  return (
    <div className="w-full h-full bg-gray-200 flex items-center justify-center">
      <p className="text-gray-400">No image</p>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════════════════
// FEATURED WORK COMPONENT
// ═══════════════════════════════════════════════════════════════════════════
export function FeaturedWork() {
  const [randomProjects, setRandomProjects] = useState<Project[]>([]);
  const [mobileProjects, setMobileProjects] = useState<Project[]>([]);
  const [scrollPosition, setScrollPosition] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const scrollContainerRef = React.useRef<HTMLDivElement>(null);
  
  const { projects, loading, error } = useProjects();

  // ─────────────────────────────────────────────────────────────────────────
  // Select 7 random projects for desktop carousel
  // ─────────────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (projects.length > 0) {
      const shuffled = [...projects].sort(() => 0.5 - Math.random());
      setRandomProjects(shuffled.slice(0, 7));
    }
  }, [projects]);

  // ─────────────────────────────────────────────────────────────────────────
  // Select 3 random projects for mobile view
  // ─────────────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (projects.length > 0) {
      const shuffled = [...projects].sort(() => 0.5 - Math.random());
      setMobileProjects(shuffled.slice(0, 3));
    }
  }, [projects]);

  // ──────────��──────────────────────────────────────────────────────────────
  // Auto-scroll effect for desktop carousel
  // ─────────────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (isPaused || !scrollContainerRef.current) return;

    const interval = setInterval(() => {
      setScrollPosition((prev) => {
        const container = scrollContainerRef.current;
        if (!container) return prev;

        const maxScroll = container.scrollWidth - container.clientWidth;
        const newPosition = prev + 1;

        // Reset to start when reaching the end
        if (newPosition >= maxScroll) {
          return 0;
        }

        return newPosition;
      });
    }, 30); // Speed: lower = faster

    return () => clearInterval(interval);
  }, [isPaused]);

  // ─────────────────────────────────────────────────────────────────────────
  // Apply scroll position to container
  // ─────────────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (scrollContainerRef.current) {
      scrollContainerRef.current.scrollLeft = scrollPosition;
    }
  }, [scrollPosition]);

  // ─────────────────────────────────────────────────────────────────────────
  // Render project card content
  // ─────────────────────────────────────────────────────────────────────────
  const renderProjectCard = (project: Project) => {
    const content = (
      <>
        <div className="relative aspect-[4/5] overflow-hidden rounded-xl bg-gray-100 mb-6">
          <div className="absolute inset-0 bg-black/5 group-hover:bg-black/10 transition-colors z-10" />
          
          <div className="w-full h-full transition-transform duration-700 group-hover:scale-105">
            {renderProjectImage(project)}
          </div>
          
          {/* Floating Metric Badge */}
          <div className="absolute top-4 right-4 z-20 bg-white/80 backdrop-blur-md border border-white/20 px-3 py-1.5 rounded-full shadow-sm">
            <span className="text-xs font-medium text-black">{project.metric}</span>
          </div>

          {/* Hover Reveal Button */}
          <div className="absolute inset-0 z-20 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="w-16 h-16 rounded-full bg-secondary text-black flex items-center justify-center transform scale-50 group-hover:scale-100 transition-transform duration-300">
              <ArrowUpRight className="w-6 h-6" />
            </div>
          </div>
        </div>

        <div>
          <p className="text-sm text-secondary font-medium mb-2">{project.category}</p>
          <h3 className="text-2xl font-bold text-black group-hover:text-black/70 transition-colors">{project.title}</h3>
        </div>
      </>
    );

    // Wrapper: External link or internal link
    if (project.externalLink) {
      return (
        <a 
          href={project.externalLink}
          target="_blank"
          rel="noopener noreferrer"
          className="block cursor-pointer"
        >
          {content}
        </a>
      );
    }

    return (
      <Link to={`/work/${project.id}`} className="block cursor-pointer">
        {content}
      </Link>
    );
  };

  return (
    <section className="py-32 bg-white overflow-hidden relative">
      <div className="container mx-auto px-6">
        {/* ────────────────────────────────────────────────────────────────── */}
        {/* Section Header */}
        {/* ─────────────────────────────────────────────────────────────────── */}
        <div className="flex justify-between items-end mb-16">
          <div>
            <AnimatedText
              as="h2"
              splitBy="words"
              stagger={0.05}
              className="text-3xl md:text-5xl font-bold tracking-tighter mb-4 text-black"
            >
              Selected Work
            </AnimatedText>
            <p className="text-black/60 text-lg">Curated projects defining the future of digital.</p>
          </div>
          <Button asChild variant="outline" className="hidden md:flex rounded-full px-6 h-12 border-black/10 btn-water btn-water-black">
            <Link to="/work">
              <ScrambleText>View All Projects</ScrambleText> <ArrowUpRight className="ml-2 w-4 h-4" />
            </Link>
          </Button>
        </div>

        {/* ─────────────────────────────────────────────────────────────────── */}
        {/* Loading State */}
        {/* ─────────────────────────────────────────────────────────────────── */}
        {loading ? (
          <div className="flex justify-center items-center h-96">
            <Loader2 className="w-10 h-10 animate-spin text-black/40" />
          </div>
        ) : error ? (
          <div className="bg-gray-50 border border-black/10 rounded-xl p-12 text-center">
            <p className="text-black/60">Failed to load projects.</p>
          </div>
        ) : randomProjects.length === 0 ? (
          <div className="bg-gray-50 border border-black/10 rounded-xl p-12 text-center">
            <p className="text-black/60">No projects available yet.</p>
          </div>
        ) : (
          <>
            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* Desktop: Auto-scrolling carousel */}
            {/* ─────────────────────────────────────────────────────────────────── */}
            <div 
              ref={scrollContainerRef}
              className="hidden md:flex gap-8 overflow-x-hidden hover:overflow-x-auto scrollbar-hide"
              onMouseEnter={() => setIsPaused(true)}
              onMouseLeave={() => setIsPaused(false)}
              style={{ scrollBehavior: 'auto' }}
            >
              {randomProjects.map((project, index) => (
                <motion.div
                  key={project.id}
                  initial={{ opacity: 0, y: 40 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-100px" }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="group relative flex-shrink-0 w-[400px]"
                >
                  {renderProjectCard(project)}
                </motion.div>
              ))}
            </div>

            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* Mobile: Static grid */}
            {/* ────────────────────────────────��────────────────────────────────── */}
            <div className="grid grid-cols-1 gap-8 md:hidden">
              {mobileProjects.map((project, index) => (
                <motion.div
                  key={project.id}
                  initial={{ opacity: 0, y: 40 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-100px" }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="group relative"
                >
                  {renderProjectCard(project)}
                </motion.div>
              ))}
            </div>
          </>
        )}
      </div>
    </section>
  );
}